#                                                              -*- Makefile -*-
# Simics module makefile
#

SIMICS_API := 4.6
THREAD_SAFE:=yes
SRC_FILES = ARINC_664MonitorMode.py

include $(MODULE_MAKEFILE)
