#                                                              -*- Makefile -*-
# Simics module makefile
#

SIMICS_API := 4.6
THREAD_SAFE:=yes
SRC_FILES = ARINC_429Mode.py

include $(MODULE_MAKEFILE)
