#                                                              -*- Makefile -*-
# Simics module makefile
#

SIMICS_API := 4.6
THREAD_SAFE:=yes

SRC_FILES = hwa_mv64560_comp.py

ifeq ($(MODULE_MAKEFILE),)
$(error Make sure you compile your module from the workspace directory)
else
include $(MODULE_MAKEFILE)
endif
